name: deploy2.yml
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Bump MAJOR no POM e exportar
        id: bump
        run: |
            set -e
            mvn -B -q build-helper:parse-version versions:set \
              -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0 \
              -DprocessAllModules -DgenerateBackupPoms=false
            
              VER="$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)"
              echo "Nova versão: $VER"
              echo "version=$VER" >> "$GITHUB_OUTPUT"
      - name: BUILD JAR
        run: mvn -B -q -DskipTests package
      - name: Copiar artefato para pasta docker
        run: |
          VERSION="${{ steps.bump.outputs.version }}"
          cp target/cervejaria-acme-$VERSION.jar docker/
      - name: LS
        run: | 
          ls docker/
      - name: Build Docker
        run: |
          cd docker
          docker build . -t leogloriainfnet/cervejaria-acme-ele:${{ steps.bump.outputs.version }}

      - name: Docker Login (Docker Hub)
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push da imagem (tag específica)
        run: |
          VERSION="${{ steps.bump.outputs.version }}"
          docker push leogloriainfnet/cervejaria-acme-ele:${{ steps.bump.outputs.version }}
      - name: Commitar pom.xml com nova versão
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: bump versão para ${{ steps.bump.outputs.version }}"
          file_pattern: pom.xml