name: deploy1.yml
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: BUILD JAR
        run: mvn -B -DskipTests package
      - name: Package artifact
        run: |
          VERSION="${GITHUB_SHA::8}-$(date +%Y%m%d%H%M%S)"
          echo "$VERSION" > version.txt
          mkdir -p bundle && cp target/*.jar bundle/app.jar
          tar czf bundle-${VERSION}.tgz -C bundle .
      - name: ADD SSH KEY
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy to EC2
        run: |
          PORT="${{ secrets.EC2_SSH_PORT || 22 }}"
          scp -o StrictHostKeyChecking=no -P "$PORT" bundle-*.tgz \
            "ec2-user@https://ec2-44-245-179-63.us-west-2.compute.amazonaws.com/:/tmp/"
