name: Running Sonar
on:
  push:
    branches:
      - main

jobs:
  build-sonar-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # p/ commitar badges
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Install Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
          cache: maven
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: m2-${{ runner.os }}-java21-${{ hashFiles('**/pom.xml', '**/.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            m2-${{ runner.os }}-java21-
            m2-${{ runner.os }}-
      - name: Cache Sonar cache
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            sonar-${{ runner.os }}-
      - name: LS
        run: |
          ls -la
      - name: Sonar Analises
        run: |
          mvn clean -DskipTests -q verify sonar:sonar -Dsonar.projectKey=Cervejaria-ACME -Dsonar.projectName='Cervejaria ACME' -Dsonar.host.url=http://ec2-35-90-57-172.us-west-2.compute.amazonaws.com:9000 -Dsonar.token=sqp_a4a372691e08b461fbc7cb35a4b4778e87d36209
