name: sonar_guard.yml
on:
  push:
    branches:
      - main
jobs:
  sonar-guard:
    runs-on: ubuntu-latest
    steps:

    - name: Contar issues abertas no Sonar
      env:
        SONAR_HOST_URL: 'http://ec2-35-90-57-172.us-west-2.compute.amazonaws.com:9000'
        SONAR_TOKEN: 'sqp_a4a372691e08b461fbc7cb35a4b4778e87d36209'
        SONAR_PROJECT_KEY: Cervejaria-ACME
        SONAR_BRANCH: main    # opcional, se quiser filtrar por branch
      run: |
        set -euo pipefail
        BASE="${SONAR_HOST_URL}/api/issues/search"
        PARAMS="componentKeys=${SONAR_PROJECT_KEY}&resolved=false&types=BUG"
        if [ -n "${SONAR_BRANCH}" ]; then
          PARAMS="${PARAMS}&branch=${SONAR_BRANCH}"
        fi
        URL="${BASE}?${PARAMS}"
        TOTAL=$(curl -sSf -u "${SONAR_TOKEN}:" "$URL" | jq -r '.total // 0')
        echo "Reliability (BUG) = ${TOTAL}"
        echo "total=${TOTAL}" >> "$GITHUB_OUTPUT"
        echo "👉 Reliability issues (OPEN/CONFIRMED) = $TOTAL"
    - name: Abrir Issue se Reliability > 10
      if: ${{ steps.sonar_rel_count.outputs.total > 5 }}
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}   # token automático do workflow
        REPO: ${{ github.repository }}
        COUNT: ${{ steps.sonar_rel_count.outputs.total }}
      run: |
        set -euo pipefail
        TITLE="[Alert] Sonar: Reliability issues acima de 10"
        BODY="Total atual de Reliability issues (OPEN/CONFIRMED): ${COUNT}\n\nAção sugerida: priorizar correções."
        curl -sSf -X POST "https://api.github.com/repos/${REPO}/issues" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg t "$TITLE" --arg b "$BODY" '{title:$t, body:$b}')"
