name: sonar_guard.yml
on:
  push:
    branches:
      - main
jobs:
  sonar-guard:
    runs-on: ubuntu-latest
    steps:

    - name: Contar issues abertas no Sonar
      env:
        SONAR_HOST_URL: 'http://ec2-35-90-57-172.us-west-2.compute.amazonaws.com:9000'
        SONAR_TOKEN: 'sqp_a4a372691e08b461fbc7cb35a4b4778e87d36209'
        SONAR_PROJECT_KEY: Cervejaria-ACME
        SONAR_BRANCH: main    # opcional, se quiser filtrar por branch
      run: |
        URL="${SONAR_HOST_URL}/api/project_issues/issues?issueStatuses=OPEN,CONFIRMED&impactSoftwareQualities=RELIABILITY&id=Cervejaria-ACME"
        TOTAL=$(curl -sSf -u "${SONAR_TOKEN}:" "$URL" | jq -r '.total // 0')
        echo "👉 Reliability issues (OPEN/CONFIRMED) = $TOTAL"